version: "3"

services:
  php:
    image: christianochapouto/phpwebserver:1.0
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
     - "80:80"
     - "443:443"
    volumes:
     - ./www:/var/www/html
    depends_on:
     - db
  db:
    image: mysql:5.7
    deploy: 
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
     - /var/lib/mysql
    environment:
     - MYSQL_ROOT_PASSWORD=phprs
     - MYSQL_DATABASE=phprs
